/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import archivo.resultado;
import archivo.palabras;
import Controlador.ControladorJugador;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;

/**
 *
 * @author kellypaltin
 */
public class VistaJuego extends javax.swing.JInternalFrame {
    private ControladorJugador controladorJugador;
    private DefaultTableModel tblModeloPalabras;
    List<String> listaPalabras;
    private palabras palabras;
    private resultado resultado;
    private int revisar = 0;
    private int intentoMaximo = 4;
    private int aciertos = 0;
    
    /**
     * 
     */
    
    public VistaJuego(ControladorJugador controladorJugador, palabras palabras, resultado resultado) {
        initComponents();
        this.controladorJugador=controladorJugador;
        this.tblModeloPalabras=(DefaultTableModel)tblPalabras.getModel();
        this.resultado=resultado;
        this.palabras=palabras;
        this.listaPalabras = new ArrayList<>();
        lblIntentos.setText("Intentos: "+intentoMaximo);
        lblAciertos.setText("Aciertos: "+aciertos);
        btnReiniciar.setVisible(false);
    }
    
    public void listaPalabrasRandom(){
        tblModeloPalabras.setRowCount(0);
        for (String palabra : palabras.leer()) {
            String dato[]={
                palabra
            };
            tblModeloPalabras.addRow(dato);
        }
    }
    
    public void comprobarLetra(){
        if (revisar==5) {
            JOptionPane.showMessageDialog(this, "HAZ ADIVINADO LA PALABRA CORRECTAMENTE! FELICIDADES!");
            aciertos++;
            lblAciertos.setText("Aciertos: "+aciertos);
            btnReiniciar.setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblJugador = new javax.swing.JLabel();
        txtJugador = new javax.swing.JTextField();
        lblIntentos = new javax.swing.JLabel();
        txtLetra = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPalabras = new javax.swing.JTable();
        btnAdivinar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtLetra1 = new javax.swing.JTextField();
        txtLetra3 = new javax.swing.JTextField();
        txtLetra2 = new javax.swing.JTextField();
        txtLetra4 = new javax.swing.JTextField();
        lblDibujo = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        lblLetra = new javax.swing.JLabel();
        txtLetra5 = new javax.swing.JTextField();
        lblAciertos = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                Cerrar(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lblJugador.setText("JUGADOR:");

        lblIntentos.setText("INTENTOS:");

        txtLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLetraActionPerformed(evt);
            }
        });
        txtLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLetraKeyTyped(evt);
            }
        });

        tblPalabras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Palabras"
            }
        ));
        jScrollPane2.setViewportView(tblPalabras);

        btnAdivinar.setText("ADIVINAR");
        btnAdivinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdivinarActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtLetra1.setEditable(false);
        txtLetra1.setText("x");
        txtLetra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLetra1ActionPerformed(evt);
            }
        });

        txtLetra3.setEditable(false);
        txtLetra3.setText("x");
        txtLetra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLetra3ActionPerformed(evt);
            }
        });

        txtLetra2.setEditable(false);
        txtLetra2.setText("x");

        txtLetra4.setEditable(false);
        txtLetra4.setText("x");
        txtLetra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLetra4ActionPerformed(evt);
            }
        });

        btnReiniciar.setText("REINICIAR");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        lblLetra.setText("INGRESE UNA LETRA:");

        txtLetra5.setEditable(false);
        txtLetra5.setText("x");
        txtLetra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLetra5ActionPerformed(evt);
            }
        });

        lblAciertos.setText("ACIERTOS:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(lblJugador)
                                .addGap(40, 40, 40)
                                .addComponent(txtJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnGuardar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLetra)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdivinar)
                        .addGap(228, 228, 228)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLetra1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLetra2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLetra3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLetra4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIntentos)
                                .addGap(97, 97, 97)
                                .addComponent(lblAciertos)))
                        .addGap(18, 18, 18)
                        .addComponent(txtLetra5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnReiniciar)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJugador)
                            .addComponent(txtJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLetra)
                            .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(btnAdivinar)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLetra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLetra4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLetra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLetra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLetra5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIntentos)
                            .addComponent(lblAciertos))
                        .addGap(33, 33, 33)
                        .addComponent(btnReiniciar)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        controladorJugador.crear(txtJugador.getText(), intentoMaximo, aciertos);
        lblJugador.setVisible(false);
        txtJugador.setVisible(false);
        btnGuardar.setVisible(false);
        lblDibujo.setIcon(new ImageIcon("/Users/kellypaltin/Desktop/JuegoDelAhorcado/src/archivo/imagen.png"));
        this.listaPalabrasRandom();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAdivinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdivinarActionPerformed
        int letras=controladorJugador.verificar(txtLetra.getText(),controladorJugador.getSeleccionado().getPalabra());
        if (letras>0 && intentoMaximo>0) {
            switch(letras){
                case 1: 
                    txtLetra1.setText(txtLetra.getText());
                    comprobarLetra();
                    revisar++;
                    break;
                    
                case 2: 
                    txtLetra2.setText(txtLetra.getText());
                    comprobarLetra();
                    revisar++;
                    break;
                    
                case 3:
                    txtLetra3.setText(txtLetra.getText());
                    comprobarLetra();
                    revisar++;
                    break;
                    
                case 4:
                    txtLetra4.setText(txtLetra.getText());
                    comprobarLetra();
                    revisar++;
                    break;
                    
                case 5:
                    txtLetra5.setText(txtLetra.getText());
                    comprobarLetra();
                    revisar++;
                    break;
            }
        }else if (letras==0) {
            intentoMaximo--;
            switch(intentoMaximo){
                case 3:
                    lblDibujo.setIcon(new ImageIcon("/Users/kellypaltin/Desktop/JuegoDelAhorcado/src/archivo/imagen1.png"));
                    break;
                case 2:
                    lblDibujo.setIcon(new ImageIcon("/Users/kellypaltin/Desktop/JuegoDelAhorcado/src/archivo/imagen2.png"));
                    break;
                case 1:
                    lblDibujo.setIcon(new ImageIcon("/Users/kellypaltin/Desktop/JuegoDelAhorcado/src/archivo/imagen3.png"));
                    break;
                case 0:
                    lblDibujo.setIcon(new ImageIcon("/Users/kellypaltin/Desktop/JuegoDelAhorcado/src/archivo/imagen4.png"));
                    JOptionPane.showMessageDialog(this, "TERMINASTE TUS INTENTOS, PERDISTE!");
                    btnReiniciar.setVisible(true);
                    break;
            }
        }
        lblIntentos.setText("Intentos: "+ intentoMaximo);
    }//GEN-LAST:event_btnAdivinarActionPerformed

    private void Cerrar(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_Cerrar
        controladorJugador.getSeleccionado().setNumeroIntentos(this.intentoMaximo);
        resultado.escribir(controladorJugador.getFicha());
    }//GEN-LAST:event_Cerrar

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        lblJugador.setVisible(true);
        txtJugador.setVisible(true);
        btnGuardar.setVisible(true);
        btnReiniciar.setVisible(false);
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void txtLetra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLetra4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLetra4ActionPerformed

    private void txtLetra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLetra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLetra1ActionPerformed

    private void txtLetra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLetra3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLetra3ActionPerformed

    private void txtLetra5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLetra5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLetra5ActionPerformed

    private void txtLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLetraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLetraActionPerformed

    private void txtLetraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLetraKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isLetter(c)&&c!=KeyEvent.VK_SPACE && c!=KeyEvent.VK_BACK_SPACE ){
            evt.consume();
            JOptionPane.showMessageDialog(this, "INGRESE UNICAMENTE UNA LETRA");
        }else{
            
        }
            
    }//GEN-LAST:event_txtLetraKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdivinar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAciertos;
    private javax.swing.JLabel lblDibujo;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblLetra;
    private javax.swing.JTable tblPalabras;
    private javax.swing.JTextField txtJugador;
    private javax.swing.JTextField txtLetra;
    private javax.swing.JTextField txtLetra1;
    private javax.swing.JTextField txtLetra2;
    private javax.swing.JTextField txtLetra3;
    private javax.swing.JTextField txtLetra4;
    private javax.swing.JTextField txtLetra5;
    // End of variables declaration//GEN-END:variables
}
